-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgBkHmZ+M6Cr1u+P3U
u1gbwj6d7g9pyoZPFQ5b/uLGmzagCgYIKoZIzj0DAQehRANCAATLAgihHShT7Cu+
CHnnZQNQJVdQDAlRdq/u2Yd20rwUkm5uHjGj/UE2fsHOVhJT1KnMfhkx50GKejGs
MiXxPY8j
-----END PRIVATE KEY-----