# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# before_all do
#   user = CredentialsManager::AppfileConfig.try_fetch_value(:apple_id)
#   keychain_entry = CredentialsManager::AccountManager.new(user: user)
#   password = keychain_entry.password

#   ENV["FASTLANE_DONT_STORE_PASSWORD"] = "1"
#   ENV["FASTLANE_USER"] = user
#   ENV["FASTLANE_PASSWORD"] = password
# end

lane :version do
  increment_build_number(xcodeproj: 'leap.xcodeproj')
end

desc 'GitHub actions release'
  lane :increment_build_upload_to_appstore do
    api_key = app_store_connect_api_key(
      key_id: 'M6922F7LHU',
      issuer_id: 'a14da7bf-8d02-4330-a8c1-98e28e0dce46',
      key_filepath: 'distribution.p8',
      duration: 1200,
      in_house: false,
    )
    create_keychain(
      name: 'ios_app_keychain',
      password: 'bigStep@2',
      timeout: 3600,
      default_keychain: true,
      unlock: true,
      lock_when_sleeps: false
    )
    match(
      readonly: true,
      type: "appstore",
      keychain_name: 'login',
      keychain_password: 'bigstep.keychain',
      shallow_clone: true,
      app_identifier: "io.playleap.rnative",
      git_url: "https://github.com/redmatch/leap/",
      clone_branch_directly: true
      # git_branch: "master"
    )

    build_app(scheme: 'leap',
              workspace:'leap.xcworkspace',
              export_method: 'app-store',
              include_bitcode:false)

    upload_to_testflight(
      app_identifier: "io.playleap.rnative",
      groups: ['playleap-rnative-internal-testers']
    )
end
